# Ref Doc: https://github.com/astral-sh/ruff-pre-commit
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.1
  hooks:
    - id: ruff
      name: Run Linter
      args: [ --fix ]
    - id: ruff-format
      name: Run formatter
