name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint with Ruff and Markdownlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: ruff check .

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or the version you need

      - name: Install Markdownlint
        run: npm install -g markdownlint-cli

      - name: Run Markdownlint
        run: markdownlint '**/*.md'
